lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
remote_theme: pages-themes/slate@v0.2.0
title: Test title
description: A short description of your site's purpose
plugins:
- jekyll-remote-theme
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
