# Overall settings
lsi: false
safe: true
source: /

# Site settings
title: CACI Network Services Blog
author:
 name: CACI Network Services
 email: info@caci.co.uk
description: "Respond to challenges before they arise with our expert led Network and Nnfrastructure consultancy services"

# Build settings
remote_theme: jekyll/minima
