# Site settings
baseurl: ""
url: "https://caci-ns.github.io"
title: CACI/CD
email: info@caci.co.uk
description: "Expert consultants in your Networking, Cloud, IT Infrastructure, DevOps and Automation challenges - adept in a wide spectrum of end-to-end services from Consulting, Deployment through to Delivery Assurance"
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Social Media settings
github_username: caci-ns
twitter_username: nscaci
twitter:
  username: nscaci
