# Site settings
baseurl: ""
url: "https://caci-ns.github.io"
title: CACI NS Blog
email: info@caci.co.uk
description: "Experts in Networks, Cloud, IT and DevOps"
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Social Media settings
github_username: caci-ns
twitter_username: nscaci
twitter:
  username: nscaci
