# Overall settings
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge/

# Site settings
baseurl: '/'
title: CACI NS Blog
email: info@caci.co.uk
description: "Experts in Networks, Cloud, Infrastructure and DevOps"
github_username: caci-ns
twitter_username: nscaci
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Build settings
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
