# Overall settings
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge/

# Site settings
title: CACI Network Services Blog
author:
 name: CACI Network Services
 email: info@caci.co.uk
description: "Respond to challenges before they arise with our expert led Network and Infrastructure consultancy services"

# Build settings
remote_theme: jekyll/minima
