name: CI - GitHub Actions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  blog-site-build:
    runs-on: "ubuntu-20.04"
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: Run Static Site Generator
        run: python site_generator.py
      - name: Commit generated HTML files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Static Site Generator-created Static HTML Site
